// Code generated by Kitex v0.15.1. DO NOT EDIT.

package mercuryalgobackendservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "mercury_algo_backend/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListBots(ctx context.Context, req *api.ListBotsRequest, callOptions ...callopt.Option) (r *api.ListBotsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMercuryAlgoBackendServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMercuryAlgoBackendServiceClient struct {
	*kClient
}

func (p *kMercuryAlgoBackendServiceClient) ListBots(ctx context.Context, req *api.ListBotsRequest, callOptions ...callopt.Option) (r *api.ListBotsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListBots(ctx, req)
}
