// Code generated by Kitex v0.15.1. DO NOT EDIT.

package mercuryalgobackendservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "mercury_algo_backend/kitex_gen/api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListBots": kitex.NewMethodInfo(
		listBotsHandler,
		newMercuryAlgoBackendServiceListBotsArgs,
		newMercuryAlgoBackendServiceListBotsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	mercuryAlgoBackendServiceServiceInfo                = NewServiceInfo()
	mercuryAlgoBackendServiceServiceInfoForClient       = NewServiceInfoForClient()
	mercuryAlgoBackendServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return mercuryAlgoBackendServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return mercuryAlgoBackendServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return mercuryAlgoBackendServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MercuryAlgoBackendService"
	handlerType := (*api.MercuryAlgoBackendService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.1",
		Extra:           extra,
	}
	return svcInfo
}

func listBotsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.MercuryAlgoBackendServiceListBotsArgs)
	realResult := result.(*api.MercuryAlgoBackendServiceListBotsResult)
	success, err := handler.(api.MercuryAlgoBackendService).ListBots(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMercuryAlgoBackendServiceListBotsArgs() interface{} {
	return api.NewMercuryAlgoBackendServiceListBotsArgs()
}

func newMercuryAlgoBackendServiceListBotsResult() interface{} {
	return api.NewMercuryAlgoBackendServiceListBotsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListBots(ctx context.Context, req *api.ListBotsRequest) (r *api.ListBotsResponse, err error) {
	var _args api.MercuryAlgoBackendServiceListBotsArgs
	_args.Req = req
	var _result api.MercuryAlgoBackendServiceListBotsResult
	if err = p.c.Call(ctx, "ListBots", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
