// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTradingBot = "trading_bot"

// TradingBot mapped from table <trading_bot>
type TradingBot struct {
	ID                         int32    `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name                       string   `gorm:"column:name;type:varchar(50);not null;uniqueIndex:name,priority:1" json:"name"`
	TradingPair                string   `gorm:"column:trading_pair;type:varchar(50);not null" json:"trading_pair"`
	ArithmeticAnnualizedReturn *float32 `gorm:"column:arithmetic_annualized_return;type:float" json:"arithmetic_annualized_return"`
	SharpeRatio                *float32 `gorm:"column:sharpe_ratio;type:float" json:"sharpe_ratio"`
	MaximumDrawdown            *float32 `gorm:"column:maximum_drawdown;type:float" json:"maximum_drawdown"`
	UserCount                  *int32   `gorm:"column:user_count;type:int" json:"user_count"`
}

// TableName TradingBot's table name
func (*TradingBot) TableName() string {
	return TableNameTradingBot
}
